// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB80eSVWUxfdXz_RDlD3eswD1O6qTR6JCY',
    appId: '1:643968082974:web:a3a2f445a1f7c29f2dba0f',
    messagingSenderId: '643968082974',
    projectId: 'disaster-app-49a53',
    authDomain: 'disaster-app-49a53.firebaseapp.com',
    storageBucket: 'disaster-app-49a53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVkEi0tCPfM8-ICgI48EssfxclZOrrezg',
    appId: '1:643968082974:android:3ced97ef6a280e0c2dba0f',
    messagingSenderId: '643968082974',
    projectId: 'disaster-app-49a53',
    storageBucket: 'disaster-app-49a53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5eYSKXTQY5LbHfsDQWkaVVYen3EeSc1A',
    appId: '1:643968082974:ios:d0f2248063a086042dba0f',
    messagingSenderId: '643968082974',
    projectId: 'disaster-app-49a53',
    storageBucket: 'disaster-app-49a53.firebasestorage.app',
    iosBundleId: 'com.example.disasterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5eYSKXTQY5LbHfsDQWkaVVYen3EeSc1A',
    appId: '1:643968082974:ios:d0f2248063a086042dba0f',
    messagingSenderId: '643968082974',
    projectId: 'disaster-app-49a53',
    storageBucket: 'disaster-app-49a53.firebasestorage.app',
    iosBundleId: 'com.example.disasterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB80eSVWUxfdXz_RDlD3eswD1O6qTR6JCY',
    appId: '1:643968082974:web:b8d9087eaa5989072dba0f',
    messagingSenderId: '643968082974',
    projectId: 'disaster-app-49a53',
    authDomain: 'disaster-app-49a53.firebaseapp.com',
    storageBucket: 'disaster-app-49a53.firebasestorage.app',
  );
}
